---
output:
  html_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 11
    highlight: tango
    theme: united
---

# Versions


Project     |  Version  |  Repository
------------|-----------|-------------
PolyJIT     | 9cfce1a   |
Likwid      | 5830615   |
isl         | e6a659e   |
isl-cpp     |	28a72cb   |
Benchbuild  | 262653a   |
Compiler-RT | fdc221a   |
Polly	      | 029f2ae   |
LLVM   	    | 4cd5308   |
Clang     	| c3709e7   |
OpenMP	    | 72db09b   |



```{r Library, echo=TRUE, include=FALSE}
library(benchbuild)
library(RPostgres)
library(DT)
library(gridExtra)
library(ggplot2)
if (!require(reshape2)) { install.packages("reshape2") }
library(reshape2)
if (!require(rpivotTable)) { install.packages("rpivotTable")}
library(rpivotTable)
library(repr)
c <- benchbuild::login("bb")
```

```{r Functions, echo=TRUE, include=FALSE}
exps <- benchbuild::get_experiments(c)
options(repr.plot.width=24, repr.plot.height=12)

plot_comparison_data <- function(selected) {
  exps <- exps[exps$id %in% selected,]$id
  plot_data <- benchbuild::region_wise_comparison(c, exps)
  return(plot_data)
}

plot_comparison <- function(plot_data) {
  plot <- ggplot(data = plot_data, aes(x=cores, y=speedup, color = cores)) +
    geom_point() +
    coord_cartesian(ylim = c(-10,10)) +
    facet_wrap(~ project)
  theme(axis.text = element_text(size = 8), axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position="none")
  return(plot)
}

scatter_plot <- function(plot_data) {
  plot <- ggplot(data = plot_data, aes(y=speedup, x=runtime_jit, color=cores)) +
    scale_x_log10() +
    geom_point(size=0.5) +
    geom_hline(yintercept=0) +
    coord_cartesian(ylim = c(-10,10)) +
    facet_wrap(~ cores) +
    geom_smooth(method=lm, se=TRUE, fullrange=TRUE, size=0.5) +
    theme(axis.text = element_text(size = 8),
          axis.text.x = element_text(angle = 45, hjust = 1))
  return(plot)
}

project_plot <- function(plot_data) {
  plot <- ggplot(data = plot_data, aes(y=speedup, x=project, color=cores)) +
    geom_point(aes(size=runtime_jit)) +
    geom_jitter() +
    geom_hline(yintercept=0) +
    coord_cartesian(ylim = c(-10,10)) +
    #facet_wrap(~ t) +
    theme(axis.text = element_text(size = 8),
          axis.text.x = element_text(angle = 45, hjust = 1))
  return(plot)
}

bar_plot <- function(plot_data) {
  plot <- ggplot(data = plot_data, aes(y=speedup, x=region_name, fill=cores)) +
    geom_bar(stat="identity", position="dodge") +
    geom_hline(yintercept=0) +
    facet_wrap(~ cores) +
    coord_cartesian(ylim = c(-10,10)) +
    scale_x_discrete() +
    scale_y_discrete(limits = c(-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10))
  theme(axis.text = element_text(size = 8))
  #,
  #      axis.text.x = element_text(angle = 45, hjust = 1))
  return(plot)
}

box_plot <- function(plot_data) {
  plot <- ggplot(data = plot_data, aes(y=speedup, x=cores)) +
    geom_hline(yintercept=0) +
    geom_violin(trim= TRUE, adjust = 1) +
    geom_boxplot(width=.1, outlier.size = 0) +
    #geom_jitter(height=0, size=0.5) +
    scale_y_discrete(limits = c(-40,-30,-20,-10,-5,-4,-3,-2,-1,0,1,2,3,4,5,10,20,30,40)) +
    coord_cartesian(ylim = c(min(plot_data$speedup),max(plot_data$speedup))) +
    xlab("Number of cores") +
    ylab("Speedup: Recompilation over baseline") +
    theme(axis.title = element_text(size = 10),
          axis.text = element_text(size = 10))
  return(plot)
}

box_plot_small <- function(plot_data, ylims, scale_limits) {
  plot <- ggplot(data = plot_data, aes(y=speedup, x=cores)) +
    geom_hline(yintercept=0) +
    geom_violin(trim= TRUE, adjust = 1) +
    geom_boxplot(width=.1, outlier.size = 0) +
    #geom_jitter(height=0, size=0.5) +
    scale_y_discrete(limits = scale_limits) +
    coord_cartesian(ylim = ylims) +
    xlab("Number of cores") +
    ylab("Speedup: Recompilation over baseline") +
    theme(axis.title = element_text(size = 10),
          axis.text = element_text(size = 10))
  return(plot)
}

data <- plot_comparison_data(
 c('395e0449-4e7f-4366-9928-eaae699be388',
   '4f74a94b-0176-4345-a9b5-c63ab1205cfe',
   '3d979f16-8d8c-4d5e-b51a-f2a6c963cfd3',
   '71ff99e8-d65c-4a36-8ee4-e6068a290eb5',
   '6005160b-fb89-4538-a982-d891f5a9f323',
   'd8fba4ac-1afb-4121-a8c0-f4c5ffd9ac16',
   '058b87a9-4e18-4dc6-a3cb-5cde41329d4d',
   '3cb17d02-4a6c-40d2-8896-f9f357e1bd9d')
 )

data$id <- paste(data$project, data$region)
data$id <- as.numeric(as.factor(data$id))
data$region_name <- c("")

data <- data[data$runtime_jit > 1000,]
data <- data[complete.cases(data),]
data <- data[!is.infinite(data$speedup),]
data <- data[!is.na(data$speedup),]

pos <- data[(as.numeric(data$cores) %in% c(1,2,3,4,5,6,7,8)),]
pos <- pos[pos$speedup < 30,]
pos <- pos[pos$speedup > 1.1,]
 
neg <- data[(as.numeric(data$cores) %in% c(1,2,3,4,5,6,7,8)),]
neg <- neg[neg$speedup < -1.1,]
neg <- neg[neg$speedup > -30,]
  
neg$t <- "bad"
pos$t <- "good"
all <- rbind(neg, pos)
```

# Complete Set

## Violins
```{r box, echo=FALSE}  
box_plot(all)
```

## Scattered
```{r scatter, echo=FALSE}  
scatter_plot(all)
```

## Projects
```{r project, echo=FALSE}
project_plot(all)
```

## Violins
```{r box_pos, echo=FALSE}
box_plot(pos)
```

## Scattered
```{r scatter_pos, echo=FALSE}
scatter_plot(pos)
```

## Projects
```{r project_pos, echo=FALSE}
project_plot(pos)
```

## Violins
```{r box_neg, echo=FALSE}
box_plot(neg)
```

## Scattered
```{r scatter_neg, echo=FALSE}
scatter_plot(neg)
```

## Projects
```{r project_neg, echo=FALSE}
project_plot(neg)
```

## Distribution of positive results

```{r plots_good, echo=FALSE}
pos_core <- data[data$cores == 5,]
pos_core <- pos_core[pos_core$speedup > 1.1,]
pos_core <- pos_core[pos_core$speedup < 10,]
regions <- levels(as.factor(pos_core$id))
pos_complete <- data[data$id %in% regions,]
box_plot(pos_complete)
pos_small <- box_plot_small(pos_complete,
                            ylims=c(-2, 10),
                            scale_limits=c(-2,-1,0,1,2,3,4,5,10))
```


# Overhead data

```{r foo, echo=FALSE}
csv <- read.csv("./data.csv")
DT::datatable(csv,
              options = list(
    style = 'bootstrap',
    class = 'table-condensed',
    paging = FALSE,
    server = TRUE))
#length(levels(as.factor(pos$project)))
#length(levels(as.factor(neg$project)))
# 
#length(levels(as.factor(neg$region_name)))
#length(levels(as.factor(pos$region_name)))
#length(levels(as.factor(all$region_name)))
# 
# csv <-read.csv("/home/simbuerg/Documents/2016/2017-PLDI-polyjit/sql/data.csv")
# mean(csv$dyncov)
# min(
#   min(csv$s2),
#   min(csv$s3),
#   min(csv$s4[!is.na(csv$s4)]),
#   min(csv$s5[!is.na(csv$s5)]))
# 
# max(
#   max(csv$s2),
#   max(csv$s3),
#   max(csv$s4[!is.na(csv$s4)]),
#   max(csv$s5[!is.na(csv$s5)]))
# 
# options(repr.plot.width=4, repr.plot.height=2)
# pos_small_data <- pos[pos$speedup<=10 & pos$cores %in% c(1,5),]
# neg_small_data <- neg[neg$speedup>=-10 & neg$cores %in% c(1,5),]
# 
# pos_small <- box_plot_small(pos_small_data,
#                             ylims=c(1, 10),
#                             scale_limits=c(1,2,3,4,5,10))
# pos_small
# 
# neg_small <- box_plot_small(neg_small_data,
#                             ylims=c(-5, -1),
#                             scale_limits=c(-5,-4,-3,-2,-1))
# neg_small
# 
# length(levels(as.factor(pos_small_data$region_name)))
# 
# 
```
